# Generated by Django 6.0.2 on 2026-03-02 11:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer Not')], max_length=20)),
                ('current_weight_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)])),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('target_weight_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)])),
                ('fitness_goal', models.CharField(choices=[('lostWeight', 'Lose Weight'), ('buildMuscle', 'Build Muscle'), ('improveEndurance', 'Improve Endurance'), ('generalWellness', 'General Wellness')], max_length=20)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('lightlyActive', 'Lightly Active'), ('moderatelyActive', 'Moderately Active'), ('veryActive', 'Very Active')], max_length=20)),
                ('dietary_preferences', models.JSONField()),
                ('dietary_other_text', models.CharField(blank=True, max_length=500)),
                ('disclaimer_accepted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
