# Generated by Django 6.0.5 on 2026-05-09 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='last_status_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
