# Generated by Django 6.0.2 on 2026-05-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='parts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
